### ISSUE TITLE
Occasional crash on MacOS in Development mode

### ISSUE THREAD

**Issue by johnmcdowall** [rails/solid_queue#205]
I'm on Sonoma 14.4.1, and when I occasionally have to restart the worker as it seems to have failed picking up jobs, I get this dumped to the console: 

```
worker | /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:977:in `set_callbacks': undefined local variable or method `__callbacks' for ActiveSupport::CurrentAttributes:Class (NameError)
worker |
worker |               self.__callbacks = __callbacks.dup
worker |                                  ^^^^^^^^^^^
worker | Did you mean?  callbacks
worker |                set_callbacks
worker |                get_callbacks
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:947:in `block (2 levels) in define_callbacks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:946:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:946:in `block in define_callbacks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:943:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:943:in `define_callbacks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/current_attributes.rb:93:in `<class:CurrentAttributes>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/current_attributes.rb:91:in `<module:ActiveSupport>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/current_attributes.rb:7:in `<main>'
worker |        from <internal:/Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
worker |        from <internal:/Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/railtie.rb:50:in `block (2 levels) in <class:Railtie>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:448:in `instance_exec'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:448:in `block in make_lambda'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:706:in `catch'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:706:in `block in default_terminator'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:203:in `block in halting'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `block in invoke_before'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `invoke_before'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:109:in `run_callbacks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:143:in `complete'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:137:in `complete!'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:81:in `ensure in block in run!'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:81:in `block in run!'
worker |        from <internal:kernel>:90:in `tap'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:75:in `run!'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:90:in `wrap'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/app_executor.rb:7:in `wrap_in_app_executor'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/processes/poller.rb:26:in `block in start_loop'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/processes/poller.rb:23:in `loop'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/processes/poller.rb:23:in `start_loop'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/processes/poller.rb:18:in `run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/processes/runnable.rb:13:in `start'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:123:in `block in start_fork'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:122:in `fork'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:122:in `start_fork'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:72:in `block in start_forks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:72:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:72:in `start_forks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:45:in `supervise'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:26:in `start'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:14:in `start'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/tasks.rb:4:in `block (2 levels) in <main>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:281:in `block in execute'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:281:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:281:in `execute'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:199:in `synchronize'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:188:in `invoke'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:188:in `invoke_task'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:138:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:138:in `block in top_level'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:147:in `run_with_threads'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:132:in `top_level'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:83:in `block in run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:214:in `standard_exception_handling'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:80:in `run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/exe/rake:27:in `<top (required)>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/bin/rake:25:in `load'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/bin/rake:25:in `<top (required)>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:492:in `exec'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `load'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
worker | /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:977:in `set_callbacks': undefined local variable or method `__callbacks' for ActiveSupport::CurrentAttributes:Class (NameError)
worker |
worker |               self.__callbacks = __callbacks.dup
worker |                                  ^^^^^^^^^^^
worker | Did you mean?  callbacks
worker |                set_callbacks
worker |                get_callbacks
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:947:in `block (2 levels) in define_callbacks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:946:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:946:in `block in define_callbacks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:943:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:943:in `define_callbacks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/current_attributes.rb:93:in `<class:CurrentAttributes>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/current_attributes.rb:91:in `<module:ActiveSupport>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/current_attributes.rb:7:in `<main>'
worker |        from <internal:/Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
worker |        from <internal:/Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/railtie.rb:49:in `block (2 levels) in <class:Railtie>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:448:in `instance_exec'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:448:in `block in make_lambda'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:706:in `catch'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:706:in `block in default_terminator'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:203:in `block in halting'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `block in invoke_before'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `invoke_before'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:109:in `run_callbacks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:129:in `run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:125:in `run!'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:78:in `block in run!'
worker |        from <internal:kernel>:90:in `tap'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:75:in `run!'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/execution_wrapper.rb:90:in `wrap'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/app_executor.rb:7:in `wrap_in_app_executor'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/processes/poller.rb:26:in `block in start_loop'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/processes/poller.rb:23:in `loop'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/processes/poller.rb:23:in `start_loop'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/processes/poller.rb:18:in `run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/processes/runnable.rb:13:in `start'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:123:in `block in start_fork'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:122:in `fork'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:122:in `start_fork'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:72:in `block in start_forks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:72:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:72:in `start_forks'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:45:in `supervise'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:26:in `start'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/supervisor.rb:14:in `start'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.3.0/lib/solid_queue/tasks.rb:4:in `block (2 levels) in <main>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:281:in `block in execute'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:281:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:281:in `execute'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:199:in `synchronize'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/task.rb:188:in `invoke'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:188:in `invoke_task'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:138:in `each'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:138:in `block in top_level'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:147:in `run_with_threads'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:132:in `top_level'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:83:in `block in run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:214:in `standard_exception_handling'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/lib/rake/application.rb:80:in `run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.0/exe/rake:27:in `<top (required)>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/bin/rake:25:in `load'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/bin/rake:25:in `<top (required)>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:492:in `exec'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `load'
worker |        from /Users/jmd/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
worker | [SolidQueue] Restarting fork[9820] (status: 1)
```

It does seem to recover, though. Feel free to close if not useful, seems to be unexpected. 

Solid Queue: 0.3.0
Rails: 7.1.3.2

**Comment by rosa** [comment]
Thanks @johnmcdowall! Looks like this is the same as https://github.com/rails/solid_queue/issues/191 🤔 I haven't been able to reproduce this myself, but there's a comment there that might be relevant.

**Comment by johnmcdowall** [comment]
Doh - sorry didn't see that. Will close this issue 👍
