### ISSUE TITLE
Updated Solid Queue erro

### ISSUE THREAD

**Issue by rctneil** [rails/solid_queue#304]
Hi,

When trying to run my app (with the puma plugin), I get this error:

```
SolidQueue-0.6.0 Error registering Supervisor(fork) (44.5ms)  pid: 12111, hostname: "d43b4061bd6a", name: "supervisor(fork)-8be0856b46aaed9d389a", error: "ActiveModel::UnknownAttributeError unknown attribute 'name' for SolidQueue::Process."
11:56:05 web.1  | SolidQueue-0.6.0 Started Supervisor(fork) (51.9ms)  pid: 12111, hostname: "d43b4061bd6a", process_id: nil, name: "supervisor(fork)-8be0856b46aaed9d389a"
```

Any ideas?

**Comment by rosa** [comment]
Hey @rctneil, yes! It looks like you're missing a migration. Could you try the instructions [here](https://github.com/rails/solid_queue/blob/main/UPGRADING.md#upgrading-to-version-06x) to fix the problem?

**Comment by rctneil** [comment]
Thankyou @rosa !

**Comment by srghma** [comment]
```
 ✘  ~/projects/newswebsite-demo  ↱ main ✚  docker compose \                                                                               <<<
        -p "newswebsite-demo_dev" \
        -f docker/demo.yml \
        run --rm solid_queue bash
[+] Creating 2/0
 ✔ Container newswebsite-demo_dev-postgres-1       Created                                                                                  0.0s
 ✔ Container newswebsite-demo_dev-elasticsearch-1  Created                                                                                  0.0s
[+] Running 2/2
 ✔ Container newswebsite-demo_dev-postgres-1       Started                                                                                  0.2s
 ✔ Container newswebsite-demo_dev-elasticsearch-1  Started                                                                                  0.2s
root@447ca48a6922:/app# /app/bin/jobs start
/usr/local/bundle/gems/activemodel-8.0.1/lib/active_model/attribute_assignment.rb:57:in 'ActiveModel::AttributeAssignment#attribute_writer_missing': unknown attribute 'name' for SolidQueue::Process. (ActiveModel::UnknownAttributeError)

      raise UnknownAttributeError.new(self, name)
      ^^^^^
        from /usr/local/bundle/gems/activemodel-8.0.1/lib/active_model/attribute_assignment.rb:74:in 'ActiveModel::AttributeAssignment#_assign_attribute'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/attribute_assignment.rb:17:in 'block in ActiveRecord::AttributeAssignment#_assign_attributes'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/attribute_assignment.rb:9:in 'Hash#each'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/attribute_assignment.rb:9:in 'ActiveRecord::AttributeAssignment#_assign_attributes'
        from /usr/local/bundle/gems/activemodel-8.0.1/lib/active_model/attribute_assignment.rb:34:in 'ActiveModel::AttributeAssignment#assign_attributes'
        from /usr/local/bundle/gems/activemodel-8.0.1/lib/active_model/api.rb:81:in 'ActiveModel::API#initialize'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/core.rb:467:in 'ActiveRecord::Core#initialize'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/inheritance.rb:76:in 'Class#new'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/inheritance.rb:76:in 'ActiveRecord::Inheritance::ClassMethods#new'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/persistence.rb:54:in 'ActiveRecord::Persistence::ClassMethods#create!'
        from /usr/local/bundle/gems/solid_queue-1.1.2/app/models/solid_queue/process.rb:13:in 'block in SolidQueue::Process.register'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in 'block in ActiveSupport::Notifications.instrument'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in 'ActiveSupport::Notifications.instrument'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue.rb:67:in 'SolidQueue#instrument'
        from /usr/local/bundle/gems/solid_queue-1.1.2/app/models/solid_queue/process.rb:12:in 'SolidQueue::Process.register'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/processes/registrable.rb:22:in 'SolidQueue::Processes::Registrable#register'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:361:in 'block in ActiveSupport::Callbacks::CallTemplate::MethodCall#make_lambda'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:207:in 'ActiveSupport::Callbacks::Filters::After#call'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:562:in 'block in ActiveSupport::Callbacks::CallbackSequence#invoke_after'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:562:in 'Array#each'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:562:in 'ActiveSupport::Callbacks::CallbackSequence#invoke_after'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:110:in 'ActiveSupport::Callbacks#run_callbacks'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/supervisor.rb:49:in 'block in SolidQueue::Supervisor#boot'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in 'block in ActiveSupport::Notifications.instrument'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in 'ActiveSupport::Notifications.instrument'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue.rb:67:in 'SolidQueue#instrument'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/supervisor.rb:48:in 'SolidQueue::Supervisor#boot'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/supervisor.rb:30:in 'SolidQueue::Supervisor#start'
        from <internal:kernel>:91:in 'Kernel#tap'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/supervisor.rb:14:in 'SolidQueue::Supervisor.start'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/cli.rb:26:in 'SolidQueue::Cli#start'
        from /usr/local/bundle/gems/thor-1.3.2/lib/thor/command.rb:28:in 'Thor::Command#run'
        from /usr/local/bundle/gems/thor-1.3.2/lib/thor/invocation.rb:127:in 'Thor::Invocation#invoke_command'
        from /usr/local/bundle/gems/thor-1.3.2/lib/thor.rb:538:in 'Thor.dispatch'
        from /usr/local/bundle/gems/thor-1.3.2/lib/thor/base.rb:584:in 'Thor::Base::ClassMethods#start'
        from /app/bin/jobs:6:in '<main>'
/usr/local/bundle/gems/activemodel-8.0.1/lib/active_model/attribute_methods.rb:512:in 'ActiveModel::AttributeMethods#method_missing': undefined method 'name=' for an instance of SolidQueue::Process (NoMethodError)
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/attribute_methods.rb:495:in 'ActiveRecord::AttributeMethods#method_missing'
        from /usr/local/bundle/gems/activemodel-8.0.1/lib/active_model/attribute_assignment.rb:69:in 'Kernel#public_send'
        from /usr/local/bundle/gems/activemodel-8.0.1/lib/active_model/attribute_assignment.rb:69:in 'ActiveModel::AttributeAssignment#_assign_attribute'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/attribute_assignment.rb:17:in 'block in ActiveRecord::AttributeAssignment#_assign_attributes'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/attribute_assignment.rb:9:in 'Hash#each'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/attribute_assignment.rb:9:in 'ActiveRecord::AttributeAssignment#_assign_attributes'
        from /usr/local/bundle/gems/activemodel-8.0.1/lib/active_model/attribute_assignment.rb:34:in 'ActiveModel::AttributeAssignment#assign_attributes'
        from /usr/local/bundle/gems/activemodel-8.0.1/lib/active_model/api.rb:81:in 'ActiveModel::API#initialize'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/core.rb:467:in 'ActiveRecord::Core#initialize'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/inheritance.rb:76:in 'Class#new'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/inheritance.rb:76:in 'ActiveRecord::Inheritance::ClassMethods#new'
        from /usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/persistence.rb:54:in 'ActiveRecord::Persistence::ClassMethods#create!'
        from /usr/local/bundle/gems/solid_queue-1.1.2/app/models/solid_queue/process.rb:13:in 'block in SolidQueue::Process.register'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in 'block in ActiveSupport::Notifications.instrument'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in 'ActiveSupport::Notifications.instrument'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue.rb:67:in 'SolidQueue#instrument'
        from /usr/local/bundle/gems/solid_queue-1.1.2/app/models/solid_queue/process.rb:12:in 'SolidQueue::Process.register'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/processes/registrable.rb:22:in 'SolidQueue::Processes::Registrable#register'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:361:in 'block in ActiveSupport::Callbacks::CallTemplate::MethodCall#make_lambda'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:207:in 'ActiveSupport::Callbacks::Filters::After#call'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:562:in 'block in ActiveSupport::Callbacks::CallbackSequence#invoke_after'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:562:in 'Array#each'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:562:in 'ActiveSupport::Callbacks::CallbackSequence#invoke_after'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:110:in 'ActiveSupport::Callbacks#run_callbacks'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/supervisor.rb:49:in 'block in SolidQueue::Supervisor#boot'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in 'block in ActiveSupport::Notifications.instrument'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
        from /usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in 'ActiveSupport::Notifications.instrument'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue.rb:67:in 'SolidQueue#instrument'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/supervisor.rb:48:in 'SolidQueue::Supervisor#boot'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/supervisor.rb:30:in 'SolidQueue::Supervisor#start'
        from <internal:kernel>:91:in 'Kernel#tap'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/supervisor.rb:14:in 'SolidQueue::Supervisor.start'
        from /usr/local/bundle/gems/solid_queue-1.1.2/lib/solid_queue/cli.rb:26:in 'SolidQueue::Cli#start'
        from /usr/local/bundle/gems/thor-1.3.2/lib/thor/command.rb:28:in 'Thor::Command#run'
        from /usr/local/bundle/gems/thor-1.3.2/lib/thor/invocation.rb:127:in 'Thor::Invocation#invoke_command'
        from /usr/local/bundle/gems/thor-1.3.2/lib/thor.rb:538:in 'Thor.dispatch'
        from /usr/local/bundle/gems/thor-1.3.2/lib/thor/base.rb:584:in 'Thor::Base::ClassMethods#start'
        from /app/bin/jobs:6:in '<main>'
```


but I have all migrations

```
root@447ca48a6922:/app# cat db/
cable_schema.rb      cache_schema.rb      migrate/             queue_structure.sql  seed_files/
cable_structure.sql  cache_structure.sql  queue_schema.rb      schema.rb            structure.sql
root@447ca48a6922:/app# cat db/migrate/
Display all 179 possibilities? (y or n)
root@447ca48a6922:/app# cat db/migrate/20250108122722_create_solid_queue_tables.solid_queue.rb
# This migration comes from solid_queue (originally 20231211200639)
class CreateSolidQueueTables < ActiveRecord::Migration[7.0]
  def change
    create_table :solid_queue_jobs do |t|
      t.string :queue_name, null: false
      t.string :class_name, null: false, index: true
      t.text :arguments
```
