### ISSUE TITLE
solid_queue_processes table doesn't exist

### ISSUE THREAD

**Issue by floydj** [rails/solid_queue#451]
Running solid_queue 1.1.0 and when I try to boot my app in development, I'm getting:

```
SolidQueue-1.1.0 Error registering Supervisor (43.0ms)  pid: 87218, hostname: "myhostname", name: "supervisor-5aaaa212e95de7696c1e", error: "ActiveRecord::StatementInvalid Mysql2::Error: Table 'purchasing_development.solid_queue_processes' doesn't exist"
```

Not sure what's going on here. I'm not trying to run solid_queue in development at all, so unsure why it's trying to access that database table. I have everything setup for solid_queue to use a separate db, so no idea why it's trying to access the application's db here.

I have run the following, but without any changes in the error:

```
bin/rails db:migrate:reset
bin/rails db:prepare
```

Any ideas what could be wrong?

**Comment by rosa** [comment]
Huh, strange! Are you running Solid Queue with Puma, perhaps?

**Comment by floydj** [comment]
I am, but not in development. Here's the stack trace:

```
07:58:16 web.1  | Puma starting in single mode...
07:58:16 web.1  | * Puma version: 6.5.0 ("Sky's Version")
07:58:16 web.1  | * Ruby version: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-darwin23]
07:58:16 web.1  | *  Min threads: 15
07:58:16 web.1  | *  Max threads: 15
07:58:16 web.1  | *  Environment: development
07:58:16 web.1  | *          PID: 24967
07:58:16 web.1  | * Listening on http://0.0.0.0:3005
07:58:16 web.1  | Use Ctrl-C to stop
07:58:16 web.1  | DEBUGGER[bin/rails#24998]: Debugger can attach via UNIX domain socket (/var/folders/6c/wgs5vc7x4hsgr0n_wgbqq22w0000gn/T/rdbg-501/rdbg-24967)
07:58:16 css.1  | $ postcss ./app/assets/builds/application-main.css --use=autoprefixer --output=./app/assets/builds/application-main.css
07:58:16 web.1  | SolidQueue-1.1.0 Error registering Supervisor (433.6ms)  pid: 24998, hostname: "camfil", name: "supervisor-67f7ee8ed4d0ee341a45", error: "ActiveRecord::StatementInvalid Mysql2::Error: Table 'purchasing_development.solid_queue_processes' doesn't exist"
07:58:16 web.1  | SolidQueue-1.1.0 Started Supervisor (458.3ms)  pid: 24998, hostname: "camfil", process_id: nil, name: "supervisor-67f7ee8ed4d0ee341a45"
07:58:16 web.1  | /Users/jasonfloyd/.gem/ruby/3.3.4/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query': Mysql2::Error: Table 'purchasing_development.solid_queue_processes' doesn't exist (ActiveRecord::StatementInvalid)
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `block in query'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `handle_interrupt'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `query'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/mysql2/database_statements.rb:98:in `block (2 levels) in raw_execute'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1004:in `block in with_raw_connection'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:976:in `with_raw_connection'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/mysql2/database_statements.rb:96:in `block in raw_execute'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1119:in `log'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/mysql2/database_statements.rb:95:in `raw_execute'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:237:in `execute_and_free'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:972:in `column_definitions'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:109:in `columns'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/schema_cache.rb:345:in `block (2 levels) in columns'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `with_connection'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/schema_cache.rb:344:in `block in columns'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/schema_cache.rb:343:in `fetch'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/schema_cache.rb:343:in `columns'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/schema_cache.rb:354:in `block in columns_hash'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/schema_cache.rb:353:in `fetch'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/schema_cache.rb:353:in `columns_hash'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/schema_cache.rb:54:in `columns_hash'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/schema_cache.rb:198:in `columns_hash'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/model_schema.rb:593:in `load_schema!'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/counter_cache.rb:187:in `load_schema!'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/encryption/encryptable_record.rb:127:in `load_schema!'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/model_schema.rb:540:in `block in load_schema'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/model_schema.rb:537:in `synchronize'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/model_schema.rb:537:in `load_schema'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/model_schema.rb:429:in `columns_hash'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/attributes.rb:244:in `block in _default_attributes'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:427:in `with_connection'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/connection_handling.rb:296:in `with_connection'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/attributes.rb:243:in `_default_attributes'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activemodel/lib/active_model/attribute_registration.rb:38:in `attribute_types'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/attribute_methods.rb:260:in `_has_attribute?'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/inheritance.rb:61:in `new'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activerecord/lib/active_record/persistence.rb:54:in `create!'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/app/models/solid_queue/process.rb:13:in `block in register'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/notifications.rb:210:in `block in instrument'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/notifications.rb:210:in `instrument'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/lib/solid_queue.rb:67:in `instrument'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/app/models/solid_queue/process.rb:12:in `register'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/lib/solid_queue/processes/registrable.rb:22:in `register'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/callbacks.rb:362:in `block in make_lambda'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/callbacks.rb:208:in `call'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/callbacks.rb:563:in `block in invoke_after'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/callbacks.rb:563:in `each'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/callbacks.rb:563:in `invoke_after'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/callbacks.rb:111:in `run_callbacks'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/lib/solid_queue/supervisor.rb:49:in `block in boot'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/notifications.rb:210:in `block in instrument'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/activesupport/lib/active_support/notifications.rb:210:in `instrument'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/lib/solid_queue.rb:67:in `instrument'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/lib/solid_queue/supervisor.rb:48:in `boot'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/lib/solid_queue/supervisor.rb:30:in `start'
07:58:16 web.1  | 	from <internal:kernel>:90:in `tap'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/lib/solid_queue/supervisor.rb:14:in `start'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/lib/puma/plugin/solid_queue.rb:17:in `block (2 levels) in start'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/lib/puma/plugin/solid_queue.rb:15:in `fork'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/solid_queue-1.1.0/lib/puma/plugin/solid_queue.rb:15:in `block in start'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/puma-6.5.0/lib/puma/events.rb:17:in `block in fire'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/puma-6.5.0/lib/puma/events.rb:17:in `each'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/puma-6.5.0/lib/puma/events.rb:17:in `fire'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/puma-6.5.0/lib/puma/events.rb:46:in `fire_on_booted!'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/puma-6.5.0/lib/puma/single.rb:58:in `run'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/puma-6.5.0/lib/puma/launcher.rb:196:in `run'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/puma-6.5.0/lib/rack/handler/puma.rb:79:in `run'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/rackup-2.2.1/lib/rackup/server.rb:341:in `start'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/railties/lib/rails/commands/server/server_command.rb:38:in `start'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/railties/lib/rails/commands/server/server_command.rb:145:in `block in perform'
07:58:16 web.1  | 	from <internal:kernel>:90:in `tap'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/railties/lib/rails/commands/server/server_command.rb:136:in `perform'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/railties/lib/rails/command/base.rb:178:in `invoke_command'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/railties/lib/rails/command/base.rb:73:in `perform'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/railties/lib/rails/command.rb:71:in `block in invoke'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/railties/lib/rails/command.rb:149:in `with_argv'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/railties/lib/rails/command.rb:69:in `invoke'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/bundler/gems/rails-9b69bc638cdd/railties/lib/rails/commands.rb:18:in `<main>'
07:58:16 web.1  | 	from <internal:/Users/jasonfloyd/.rubies/ruby-3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
07:58:16 web.1  | 	from <internal:/Users/jasonfloyd/.rubies/ruby-3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
07:58:16 web.1  | 	from /Users/jasonfloyd/.gem/ruby/3.3.4/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
07:58:16 web.1  | 	from bin/rails:4:in `<main>'
```

**Comment by onelinetree** [comment]
Hi floydj, I had a similar problem.
Just try to add something like this to `application.rb` somewhere inside the `class Application < Rails::Application block`
```
config.active_job.queue_adapter = :solid_queue
config.solid_queue.connects_to = { database: { writing: :queue } }
```
That solved a comparable error in my rails app.
Don't know if a newly created rails app should add this by default 
I'm also using a separate DB for solid queue, that might cause the problem(?) – but don't know for sure.

**Comment by rosa** [comment]
Thanks @onelinetree! It seems @floydj's error is different because he's not trying to run solid queue in development. 

Sorry for the delay replying. I think you're running Solid Queue with Puma in development as well, not just production, so that's why it's getting started. How are you adding the Solid Queue plugin to your Puma configuration?

**Comment by floydj** [comment]
I had it in the config/puma.rb file as 

`plugin :solid_queue`

But I see in Rails 8 that it's been changed to `plugin :solid_queue if ENV["SOLID_QUEUE_IN_PUMA"]`. And making that change fixes up my development environment.

Should the `if ENV["SOLID_QUEUE_IN_PUMA"]` part be added to the README, which is what I was following?

**Comment by rosa** [comment]
Ahhh, perfect. Yes, that's what Rails 8 adds by default, not only because of development, but because many people would prefer to start solid queue separately via `bin/jobs`. 

Not sure about adding that to the `README`, because it tells you how to configure Solid Queue to be run with Puma, so if you add that it's because you want to run it with Puma, and so you need to take care of doing that in the environment you wish? 🤔

**Comment by floydj** [comment]
Yeah, I mean, I know that's on me, but I just blindly followed what the `README` showed, and it led to this problem for me, because I use Puma in development. But I get what you're saying. Thanks for following up, I actually fixed this up a couple days ago, but forgot to report back here.

**Comment by rosa** [comment]
Yeah, makes sense! I'll add a note about it in the README in any case, if that can avoid someone's confusion! Thank you 🙏

**Comment by rosa** [comment]
Done in https://github.com/rails/solid_queue/commit/eb75d093bcbe31c6d750549e2a28925074b42a78
